[project]
name = "Transcriber9000ProMax"
version = "0.1.0"
description = "Hehehe"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gigaam[torch]",
    "kenlm",
    "pydantic>=2.13.4",
    "tone[demo]",
]

[tool.uv]
override-dependencies = [
    "numpy>=2.0.0",
]

[tool.uv.sources]
tone = { git = "https://github.com/voicekit-team/T-one.git", rev = "3c5b6c015038173840e62cea99e10cdb1c759116" }
kenlm = { git = "https://github.com/kpu/kenlm.git", rev = "4cb443e60b7bf2c0ddf3c745378f76cb59e254e5" }
gigaam = { git = "https://github.com/salute-developers/GigaAM.git", rev = "6e4b027c6fb554e09e8b9059b757a175295ab879" }

[tool.basedpyright]
ignore = [
    "test.py"
]
typeCheckingMode = "recommended"

[dependency-groups]
dev = [
    "basedpyright>=1.39.4",
    "pre-commit>=4.6.0",
    "ruff>=0.15.12",
]
